export const GITHUB_OPERATIONS_ERROR_CODES = {
  CONFIGURATION: 'GITHUB_OPERATIONS_CONFIGURATION',
  INSTALLATION_NOT_FOUND: 'GITHUB_OPERATIONS_INSTALLATION_NOT_FOUND',
  ORGANIZATION_MISMATCH: 'GITHUB_OPERATIONS_ORGANIZATION_MISMATCH',
  AUTHENTICATION: 'GITHUB_OPERATIONS_AUTHENTICATION',
  PERMISSION: 'GITHUB_OPERATIONS_PERMISSION',
  RATE_LIMITED: 'GITHUB_OPERATIONS_RATE_LIMITED',
  UPSTREAM: 'GITHUB_OPERATIONS_UPSTREAM',
  INVALID_RESPONSE: 'GITHUB_OPERATIONS_INVALID_RESPONSE',
  INVALID_INPUT: 'GITHUB_OPERATIONS_INVALID_INPUT',
  INVITATION_LIMIT: 'GITHUB_OPERATIONS_INVITATION_LIMIT',
} as const;

export type GithubOperationsErrorCode =
  (typeof GITHUB_OPERATIONS_ERROR_CODES)[keyof typeof GITHUB_OPERATIONS_ERROR_CODES];

export class GithubOperationsError extends Error {
  override readonly name = 'GithubOperationsError';

  constructor(
    readonly code: GithubOperationsErrorCode,
    readonly retryable: boolean,
    readonly retryAt: Date | null = null,
  ) {
    super(code);
  }
}
