import { execFileSync } from 'node:child_process';
import { readdirSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';

const repo = path.resolve(import.meta.dirname, '..');
const pkgDir = path.join(repo, 'apps/frontend');
const tsc = path.join(pkgDir, 'node_modules/.bin/tsc');
const tsconfig = path.join(repo, '.design-sync/tsconfig.dts.json');

try {
  execFileSync(tsc, ['-p', tsconfig], { stdio: 'inherit' });
} catch {
  console.error('  ! tsc reported diagnostics — declarations still emitted');
}

const typesDir = path.join(pkgDir, 'ds-types');
if (!existsSync(typesDir)) {
  console.error('[TYPES] emit 실패 — ds-types/ 없음');
  process.exit(1);
}

const uiDir = path.join(typesDir, 'components/ui');
const ui = existsSync(uiDir)
  ? readdirSync(uiDir)
      .filter((f) => f.endsWith('.d.ts'))
      .map((f) => f.replace(/\.d\.ts$/, ''))
      .sort()
  : [];

const lines = [
  '// GENERATED by .design-sync/emit-types.mjs — 편집하지 않는다.',
  '// design-sync가 컴포넌트 export 집합과 inline props를 해석하기 위한 진입 모듈.',
  "export * from './ds-types/components';",
  ...ui.map((n) => `export * from './ds-types/components/ui/${n}';`),
  '',
].join('\n');

writeFileSync(path.join(pkgDir, 'index.d.ts'), lines);
const count = readdirSync(path.join(typesDir, 'components')).filter((f) =>
  f.endsWith('.d.ts'),
).length;
console.error(
  `[TYPES] ${count} component + ${ui.length} ui 선언 → ds-types/, index.d.ts 생성`,
);
