// design-sync: 컴포넌트 prop 계약(.d.ts)을 생성한다.
//
// 왜 필요한가 — apps/frontend는 라이브러리가 아니라 Next 앱이라 published dist/도
// .d.ts 트리도 없다. 그대로 두면 converter가 모든 컴포넌트를
// `[key: string]: unknown`으로 내보내고, 그 파일이 design agent가 코딩하는
// API 계약이 되어 전 컴포넌트를 오용하게 된다.
//
// 하는 일 두 가지:
//  1. tsc로 src/components + src/lib의 선언을 apps/frontend/ds-types/에 emit.
//     dot 디렉터리는 converter의 glob(dot:false)이 건너뛰므로 이름에 점을 쓰지 않는다.
//  2. apps/frontend/index.d.ts 진입 모듈 생성 — dts 추출기가
//     `React.ComponentProps<'button'> & VariantProps<…>`처럼 named interface가
//     아닌 inline props를 해석하려면 resolvable한 entry 모듈이 있어야 한다.
//     (이게 없으면 Button/StatusBadge 등 shadcn 계열이 전부 빈 계약이 된다.)
//
// 둘 다 gitignore 대상이며 앱 런타임·CI와 무관하다.
import { execFileSync } from 'node:child_process';
import { readdirSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';

const repo = path.resolve(import.meta.dirname, '..');
const pkgDir = path.join(repo, 'apps/frontend');
const tsc = path.join(pkgDir, 'node_modules/.bin/tsc');
const tsconfig = path.join(repo, '.design-sync/tsconfig.dts.json');

// 1. 선언 emit — 타입 에러가 있어도 tsc는 기본적으로 emit한다(noEmitOnError 미설정).
try {
  execFileSync(tsc, ['-p', tsconfig], { stdio: 'inherit' });
} catch {
  console.error('  ! tsc reported diagnostics — declarations still emitted');
}

const typesDir = path.join(pkgDir, 'ds-types');
if (!existsSync(typesDir)) {
  console.error('[TYPES] emit 실패 — ds-types/ 없음');
  process.exit(1);
}

// 2. 진입 모듈 — 배럴(합성 컴포넌트) + ui 프리미티브 각 모듈.
// 배럴은 ui/를 re-export하지 않으므로 심볼이 겹치지 않는다.
const uiDir = path.join(typesDir, 'components/ui');
const ui = existsSync(uiDir)
  ? readdirSync(uiDir)
      .filter((f) => f.endsWith('.d.ts'))
      .map((f) => f.replace(/\.d\.ts$/, ''))
      .sort()
  : [];

const lines = [
  '// GENERATED by .design-sync/emit-types.mjs — 편집하지 않는다.',
  '// design-sync가 컴포넌트 export 집합과 inline props를 해석하기 위한 진입 모듈.',
  "export * from './ds-types/components';",
  ...ui.map((n) => `export * from './ds-types/components/ui/${n}';`),
  '',
].join('\n');

writeFileSync(path.join(pkgDir, 'index.d.ts'), lines);
const count = readdirSync(path.join(typesDir, 'components')).filter((f) =>
  f.endsWith('.d.ts'),
).length;
console.error(
  `[TYPES] ${count} component + ${ui.length} ui 선언 → ds-types/, index.d.ts 생성`,
);
