export const EXPECTED_APP_CONTROLLER_NAMES = [
  'AccountDeactivationController',
  'AdminAccessController',
  'ApplicationDecisionNotificationsController',
  'ApplicationTemplatesController',
  'ApplicationsController',
  'AuditLogController',
  'AuthController',
  'BoardController',
  'CollectionAdminController',
  'ConsentsController',
  'DeadlineDigestController',
  'DeadlineDigestFailuresController',
  'HealthController',
  'IndependentAuthorityController',
  'LoginHistoryController',
  'MilestoneDocumentCurrentFileController',
  'MilestoneDocumentFilesController',
  'MilestoneDocumentsController',
  'MilestonesController',
  'NotificationSettingsController',
  'OnboardingController',
  'ProgramApplicationsController',
  'ProgramAuthoringController',
  'ProgramEditorController',
  'ProgramOverviewController',
  'ProgramTeamsController',
  'ProgramsController',
  'PublicProjectsController',
  'PublicUserProfileController',
  'RankingController',
  'RepositoriesController',
  'StaffAccessRequestsController',
  'StaffDashboardController',
  'StudentApplicationsController',
  'StudentDashboardController',
  'SubmissionChecklistController',
  'SubmissionFileCleanupFailuresController',
  'SubmissionFilesController',
  'SubmissionFormsController',
  'SubmissionMatrixController',
  'SubmissionRepositoryPublishingController',
  'SubmissionReviewsController',
  'SubmissionsController',
  'SystemStatusController',
  'TeamInvitationsController',
  'UsersController',
] as const;

function route(
  method: string,
  path: string,
  access: 'PUBLIC' | 'OPTIONAL_SESSION' | 'PROTECTED',
) {
  return { method, path, access } as const;
}

export const EXPECTED_PUBLIC_AUTH_ROUTES = [
  route('GET', '/api/v1/auth/github', 'PUBLIC'),
  route('GET', '/api/v1/auth/github/callback', 'PUBLIC'),
  route('GET', '/api/v1/health', 'PUBLIC'),
  route('GET', '/api/v1/programs/:id', 'PUBLIC'),
  route('GET', '/api/v1/programs/:programId/overview/teams', 'PUBLIC'),
  route('GET', '/api/v1/programs/application-templates', 'PUBLIC'),
  route('GET', '/api/v1/programs/status-counts', 'PUBLIC'),
  route('GET', '/api/v1/projects', 'PUBLIC'),
  route('GET', '/api/v1/projects/:projectId', 'PUBLIC'),
  route('GET', '/api/v1/projects/category-counts', 'PUBLIC'),
  route('GET', '/api/v1/ranking/years', 'PUBLIC'),
  route('GET', '/api/v1/users/:userId/public-profile', 'PUBLIC'),
  route('POST', '/api/v1/auth/logout', 'PUBLIC'),
] as const;

export const EXPECTED_OPTIONAL_SESSION_AUTH_ROUTES = [
  route('GET', '/api/v1/auth/session', 'OPTIONAL_SESSION'),
  route('GET', '/api/v1/programs', 'OPTIONAL_SESSION'),
  route('GET', '/api/v1/ranking', 'OPTIONAL_SESSION'),
] as const;

export const EXPECTED_INDEPENDENT_AUTHORITY_PROTECTED_ROUTES = [
  route('GET', '/api/v1/users/:id/access', 'PROTECTED'),
  route('PATCH', '/api/v1/users/:id/admin-access', 'PROTECTED'),
  route('PATCH', '/api/v1/users/:id/staff-access', 'PROTECTED'),
] as const;

export const EXPECTED_AUTH_ROUTE_INVENTORY = [
  'PROTECTED DELETE /api/v1/milestones/:id',
  'PROTECTED DELETE /api/v1/milestones/:milestoneId/documents/:documentId',
  'PROTECTED DELETE /api/v1/program-authoring/uploads/:id',
  'PROTECTED DELETE /api/v1/programs/:id',
  'PROTECTED DELETE /api/v1/programs/:id/purge',
  'PROTECTED DELETE /api/v1/programs/:programId/applications/me',
  'PROTECTED DELETE /api/v1/programs/:programId/board/posts/:postId',
  'PROTECTED DELETE /api/v1/programs/:programId/board/posts/:postId/comments/:commentId',
  'PROTECTED GET /api/v1/admin/collection/invariants',
  'PROTECTED GET /api/v1/admin/collection/runs',
  'PROTECTED GET /api/v1/applications/:id',
  'PROTECTED GET /api/v1/audit-logs',
  'PUBLIC GET /api/v1/auth/github',
  'PUBLIC GET /api/v1/auth/github/callback',
  'OPTIONAL_SESSION GET /api/v1/auth/session',
  'PROTECTED GET /api/v1/consents/current',
  'PROTECTED GET /api/v1/dashboard/staff/insights',
  'PROTECTED GET /api/v1/dashboard/staff/summary',
  'PROTECTED GET /api/v1/dashboard/student',
  'PROTECTED GET /api/v1/dashboard/student/activity-timeline',
  'PUBLIC GET /api/v1/health',
  'PROTECTED GET /api/v1/milestones/:milestoneId/documents',
  'PROTECTED GET /api/v1/milestones/:milestoneId/documents/:documentId/applications/:applicationId/file',
  'PROTECTED GET /api/v1/milestones/:milestoneId/documents/:documentId/submissions/current/file',
  'PROTECTED GET /api/v1/milestones/:milestoneId/documents/:documentId/template',
  'PROTECTED GET /api/v1/milestones/:milestoneId/documents/collection',
  'PROTECTED GET /api/v1/milestones/:milestoneId/documents/collection/archive',
  'PROTECTED GET /api/v1/notifications/deadline-digests/failures',
  'PROTECTED GET /api/v1/onboarding/role',
  'OPTIONAL_SESSION GET /api/v1/programs',
  'PUBLIC GET /api/v1/programs/:id',
  'PROTECTED GET /api/v1/programs/:id/activity',
  'PROTECTED GET /api/v1/programs/:id/edit',
  'PROTECTED GET /api/v1/programs/:id/viewer',
  'PROTECTED GET /api/v1/programs/:programId/applications',
  'PROTECTED GET /api/v1/programs/:programId/applications/me',
  'PROTECTED GET /api/v1/programs/:programId/board/posts',
  'PROTECTED GET /api/v1/programs/:programId/board/posts/:postId',
  'PROTECTED GET /api/v1/programs/:programId/milestones/:milestoneId/submission-form',
  'PROTECTED GET /api/v1/programs/:programId/overview',
  'PUBLIC GET /api/v1/programs/:programId/overview/teams',
  'PROTECTED GET /api/v1/programs/:programId/submissions/matrix',
  'PROTECTED GET /api/v1/programs/:programId/submissions/me',
  'PROTECTED GET /api/v1/programs/:programId/teams',
  'PROTECTED GET /api/v1/programs/:programId/teams/:teamId',
  'PROTECTED GET /api/v1/programs/:programId/teams/me',
  'PUBLIC GET /api/v1/programs/application-templates',
  'PUBLIC GET /api/v1/programs/status-counts',
  'PUBLIC GET /api/v1/projects',
  'PUBLIC GET /api/v1/projects/:projectId',
  'PUBLIC GET /api/v1/projects/category-counts',
  'OPTIONAL_SESSION GET /api/v1/ranking',
  'PUBLIC GET /api/v1/ranking/years',
  'PROTECTED GET /api/v1/repositories/me',
  'PROTECTED GET /api/v1/role-requests/me',
  'PROTECTED GET /api/v1/submission-files/:fileId',
  'PROTECTED GET /api/v1/submission-files/cleanup/failures',
  'PROTECTED GET /api/v1/submissions/:submissionId/review-context',
  'PROTECTED GET /api/v1/system-status',
  'PROTECTED GET /api/v1/team-invitations/received',
  'PROTECTED GET /api/v1/team-invitations/teams/:teamId/search',
  'PROTECTED GET /api/v1/team-invitations/teams/:teamId/sent',
  'PROTECTED GET /api/v1/users/:id/access',
  'PROTECTED GET /api/v1/users/:id/access/history',
  'PUBLIC GET /api/v1/users/:userId/public-profile',
  'PROTECTED GET /api/v1/users/access',
  'PROTECTED GET /api/v1/users/access/facets',
  'PROTECTED GET /api/v1/users/access/requests',
  'PROTECTED GET /api/v1/users/me/login-history',
  'PROTECTED GET /api/v1/users/me/notification-email',
  'PROTECTED GET /api/v1/users/me/notifications/application-decisions',
  'PROTECTED GET /api/v1/users/me/profile',
  'PROTECTED PATCH /api/v1/applications/:id',
  'PROTECTED PATCH /api/v1/milestones/:id',
  'PROTECTED PATCH /api/v1/milestones/:milestoneId/documents/:documentId',
  'PROTECTED PATCH /api/v1/milestones/:milestoneId/documents/order',
  'PROTECTED PATCH /api/v1/programs/:id',
  'PROTECTED PATCH /api/v1/programs/:id/lifecycle',
  'PROTECTED PATCH /api/v1/programs/:programId/applications/me',
  'PROTECTED PATCH /api/v1/programs/:programId/board/posts/:postId',
  'PROTECTED PATCH /api/v1/programs/:programId/board/posts/:postId/pin',
  'PROTECTED PATCH /api/v1/users/:id/access',
  'PROTECTED PATCH /api/v1/users/:id/admin-access',
  'PROTECTED PATCH /api/v1/users/:id/profile',
  'PROTECTED PATCH /api/v1/users/:id/staff-access',
  'PROTECTED PATCH /api/v1/users/me/account/deactivate',
  'PROTECTED PATCH /api/v1/users/me/notification-email',
  'PROTECTED PATCH /api/v1/users/me/notifications/application-decisions/:notificationId/read',
  'PROTECTED PATCH /api/v1/users/me/profile',
  'PROTECTED POST /api/v1/admin/collection/discover-external',
  'PROTECTED POST /api/v1/admin/collection/trigger',
  'PUBLIC POST /api/v1/auth/logout',
  'PROTECTED POST /api/v1/consents',
  'PROTECTED POST /api/v1/milestone-document-files',
  'PROTECTED POST /api/v1/milestones/:milestoneId/documents',
  'PROTECTED POST /api/v1/milestones/:milestoneId/documents/:documentId/applications/:applicationId/reviews',
  'PROTECTED POST /api/v1/milestones/:milestoneId/documents/:documentId/submissions',
  'PROTECTED POST /api/v1/milestones/:milestoneId/documents/:documentId/template',
  'PROTECTED POST /api/v1/onboarding/role',
  'PROTECTED POST /api/v1/program-authoring/programs',
  'PROTECTED POST /api/v1/program-authoring/uploads',
  'PROTECTED POST /api/v1/programs',
  'PROTECTED POST /api/v1/programs/:id/milestones',
  'PROTECTED POST /api/v1/programs/:programId/applications',
  'PROTECTED POST /api/v1/programs/:programId/board/posts',
  'PROTECTED POST /api/v1/programs/:programId/board/posts/:postId/comments',
  'PROTECTED POST /api/v1/programs/:programId/deadline-digest/preview',
  'PROTECTED POST /api/v1/programs/:programId/deadline-digest/send',
  'PROTECTED POST /api/v1/programs/:programId/teams',
  'PROTECTED POST /api/v1/programs/:programId/teams/join',
  'PROTECTED POST /api/v1/repositories/:repositoryId/publish',
  'PROTECTED POST /api/v1/role-requests',
  'PROTECTED POST /api/v1/submission-files',
  'PROTECTED POST /api/v1/submissions',
  'PROTECTED POST /api/v1/submissions/:submissionId/resubmissions',
  'PROTECTED POST /api/v1/submissions/:submissionId/reviews',
  'PROTECTED POST /api/v1/team-invitations/:invitationId/accept',
  'PROTECTED POST /api/v1/team-invitations/:invitationId/cancel',
  'PROTECTED POST /api/v1/team-invitations/:invitationId/decline',
  'PROTECTED POST /api/v1/team-invitations/teams/:teamId/invitations',
  'PROTECTED POST /api/v1/users/me/profile',
] as const;
