/**
 * G003 durable production env snapshot.
 * Raw values only — no trim/default/validate; façades keep per-key semantics.
 */

export const RUNTIME_CONFIG_KEYS = [
  'NODE_ENV',
  'AUTH_INITIAL_ROLES',
  'SESSION_SECRET',
  'FRONTEND_URL',
  'GITHUB_OAUTH_CLIENT_ID',
  'GITHUB_OAUTH_CLIENT_SECRET',
  'GITHUB_OAUTH_CALLBACK_URL',
  'GITHUB_APP_ORG',
  'GITHUB_COLLECTION_APP_ID',
  'GITHUB_COLLECTION_APP_PRIVATE_KEY',
  'GITHUB_COLLECTION_APP_API_BASE_URL',
  'GITHUB_COLLECTION_APP_MAX_PAGES',
  'GITHUB_COLLECTION_APP_DEADLINE_MS',
  'GITHUB_COLLECTION_APP_SMOKE_PUBLIC_ALIASES',
  'GITHUB_COLLECTION_APP_SMOKE_PRIVATE_ALIAS',
  'COLLECTION_CRON_EXPRESSION',
  'GITHUB_OPERATIONS_APP_ID',
  'GITHUB_OPERATIONS_APP_PRIVATE_KEY',
  'PORT',
  'GMAIL_SENDER',
  'GMAIL_OAUTH_CLIENT_ID',
  'GMAIL_OAUTH_CLIENT_SECRET',
  'GMAIL_OAUTH_REFRESH_TOKEN',
  'DIGEST_FORCE_TO',
  'TEAM_JOIN_CODE_SECRET',
  'SUBMISSION_FILE_S3_ENDPOINT',
  'SUBMISSION_FILE_S3_REGION',
  'SUBMISSION_FILE_S3_BUCKET',
  'SUBMISSION_FILE_S3_ACCESS_KEY_ID',
  'SUBMISSION_FILE_S3_SECRET_ACCESS_KEY',
  'SUBMISSION_FILE_S3_FORCE_PATH_STYLE',
  'SUBMISSION_FILE_CLEANUP_OPERATOR_ID',
  'SUBMISSION_FILE_CLEANUP_MAINTENANCE_ENABLED',
  'MAIL_MODE',
] as const;

export type RuntimeEnvKey = (typeof RUNTIME_CONFIG_KEYS)[number];

export type RuntimeConfig = Readonly<{
  [K in RuntimeEnvKey]: string | undefined;
}>;

/**
 * Pure snapshot of production env keys. Explicit `env.KEY` reads keep the
 * AST contract scanner aligned with RUNTIME_CONFIG_KEYS as the manifest.
 */
export function loadRuntimeConfig(env: NodeJS.ProcessEnv): RuntimeConfig {
  return Object.freeze({
    NODE_ENV: env.NODE_ENV,
    AUTH_INITIAL_ROLES: env.AUTH_INITIAL_ROLES,
    SESSION_SECRET: env.SESSION_SECRET,
    FRONTEND_URL: env.FRONTEND_URL,
    GITHUB_OAUTH_CLIENT_ID: env.GITHUB_OAUTH_CLIENT_ID,
    GITHUB_OAUTH_CLIENT_SECRET: env.GITHUB_OAUTH_CLIENT_SECRET,
    GITHUB_OAUTH_CALLBACK_URL: env.GITHUB_OAUTH_CALLBACK_URL,
    GITHUB_APP_ORG: env.GITHUB_APP_ORG,
    GITHUB_COLLECTION_APP_ID: env.GITHUB_COLLECTION_APP_ID,
    GITHUB_COLLECTION_APP_PRIVATE_KEY: env.GITHUB_COLLECTION_APP_PRIVATE_KEY,
    GITHUB_COLLECTION_APP_API_BASE_URL: env.GITHUB_COLLECTION_APP_API_BASE_URL,
    GITHUB_COLLECTION_APP_MAX_PAGES: env.GITHUB_COLLECTION_APP_MAX_PAGES,
    GITHUB_COLLECTION_APP_DEADLINE_MS: env.GITHUB_COLLECTION_APP_DEADLINE_MS,
    GITHUB_COLLECTION_APP_SMOKE_PUBLIC_ALIASES:
      env.GITHUB_COLLECTION_APP_SMOKE_PUBLIC_ALIASES,
    GITHUB_COLLECTION_APP_SMOKE_PRIVATE_ALIAS:
      env.GITHUB_COLLECTION_APP_SMOKE_PRIVATE_ALIAS,
    COLLECTION_CRON_EXPRESSION: env.COLLECTION_CRON_EXPRESSION,
    GITHUB_OPERATIONS_APP_ID: env.GITHUB_OPERATIONS_APP_ID,
    GITHUB_OPERATIONS_APP_PRIVATE_KEY: env.GITHUB_OPERATIONS_APP_PRIVATE_KEY,
    PORT: env.PORT,
    GMAIL_SENDER: env.GMAIL_SENDER,
    GMAIL_OAUTH_CLIENT_ID: env.GMAIL_OAUTH_CLIENT_ID,
    GMAIL_OAUTH_CLIENT_SECRET: env.GMAIL_OAUTH_CLIENT_SECRET,
    GMAIL_OAUTH_REFRESH_TOKEN: env.GMAIL_OAUTH_REFRESH_TOKEN,
    DIGEST_FORCE_TO: env.DIGEST_FORCE_TO,
    TEAM_JOIN_CODE_SECRET: env.TEAM_JOIN_CODE_SECRET,
    SUBMISSION_FILE_S3_ENDPOINT: env.SUBMISSION_FILE_S3_ENDPOINT,
    SUBMISSION_FILE_S3_REGION: env.SUBMISSION_FILE_S3_REGION,
    SUBMISSION_FILE_S3_BUCKET: env.SUBMISSION_FILE_S3_BUCKET,
    SUBMISSION_FILE_S3_ACCESS_KEY_ID: env.SUBMISSION_FILE_S3_ACCESS_KEY_ID,
    SUBMISSION_FILE_S3_SECRET_ACCESS_KEY:
      env.SUBMISSION_FILE_S3_SECRET_ACCESS_KEY,
    SUBMISSION_FILE_S3_FORCE_PATH_STYLE:
      env.SUBMISSION_FILE_S3_FORCE_PATH_STYLE,
    SUBMISSION_FILE_CLEANUP_OPERATOR_ID:
      env.SUBMISSION_FILE_CLEANUP_OPERATOR_ID,
    SUBMISSION_FILE_CLEANUP_MAINTENANCE_ENABLED:
      env.SUBMISSION_FILE_CLEANUP_MAINTENANCE_ENABLED,
    MAIL_MODE: env.MAIL_MODE,
  });
}
