export const PROGRAM_EDIT_ERROR_CODES = {
  VALIDATION_ERROR: 'PRG_001',
  FORBIDDEN: 'PRG_002',
  STAFF_APPROVAL_REQUIRED: 'PRG_003',
  PROGRAM_NOT_FOUND: 'PRG_004',
  MILESTONE_NOT_FOUND: 'PRG_005',
  CATEGORY_LOCKED_BY_APPLICATIONS: 'PRG_006',
  INVALID_APPLICATION_PERIOD: 'PRG_007',
  MILESTONE_BEFORE_APPLICATION_END: 'PRG_008',
  MILESTONE_HAS_SUBMISSIONS: 'PRG_009',
  MILESTONE_REQUIRED: 'PRG_010',
} as const;

export type ProgramEditErrorCode =
  (typeof PROGRAM_EDIT_ERROR_CODES)[keyof typeof PROGRAM_EDIT_ERROR_CODES];
